version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: anything
      POSTGRES_USER: anything
      POSTGRES_PASSWORD: a_secure_anything
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init.sql script

  cash-chan:
    image: cash-chan
    depends_on:
      - postgres
    ports:
      - "3333:3333"

volumes:  # Named volumes ; probably somewhere in /var/lib/docker/volumes/
  postgres_data:
