apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOREEwTWprdwpOak0yTkRKYUZ3MDBOREEwTWprd05qTTJOREphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFESFhKcUk2UGJIZms5YjhsNTZoZjRyY2xweXJiQzhMcERPWWpGYTlxdTJyU3o2OERBSQpENzliZm5QajRoVldjZldpbEZuT1hPT2FISTd0L2x1VlEwWXVaSXlNdWZwYm1ZWG5qY3JySFFqWW84eVVOWHVOCnlhZXlKTm9KSm9xc0Z5bUdoekRvYXg5VmI1SGlZOVVZbUh2Qi9wcUVQbU13RnVMS0JBMEEzL1Rqbi9pV1czYVIKdGhkS3Vua3VYUHNJYk9NVmNFWU85RUJDc0psYlVWRjRvS0VOaUhEVSswdG9naVRVQWNQRUliUTdoYkxDSnlHTwpGYlVpbndzNlIzcTk0MnZEd1NGWERSeGc4d3ppNEdXNTN3aUdJSnJtKzdOaTB0Y0ZBR1ZZSUZ2T0F4T3F4OU9TClV3aW8xWmhOUXZ1OWtkL2hEMGIralNhZ2JER0JxaTBDcVRiSkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNPRGtLcDNJTVd2QVhWRWU4WgpTdkZmUkljME1EQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFtbHB4Ykk0ZE00a0lpaER5UXFDTUdBd3gvUVdTCkxWODdYSmdpaHpidmpzVHV6aG5vS3NURlM4czVyckNNakVNUVZSMHRrTy9NOWRhdTg1aDR5MGhpek5rdzRKWmkKRzZiNFZiSWN3aS9kRUZIbXJSKzkyYTlEemxJSkhRK0pibHQzSXNRZzVIbmJaeEVqdFExVXJMQk1uWHc5VlVWdwpmZXBESU1HUUFKeXRmWHYvd1U4WlNsMlFzSjEzc1ZZRktSL09KcW80NER1ZXZDeFJiRWhVTjMzWkUydXhQdCtjCjhiSFM5YTZ3SStNVURnNWQyYk5CV1hmSXpKME1JTlB2MlZFS0lDOGFrQWZWb08yTTZITU14dGZYbnJnSGl5TUEKa1Vzemkra0lhc1RVYWpVN3dla29JWk9nWFplUnFJK0NmRlNydXlTcklCZDVBa2dXNVFOOXR6R2xvUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: 162.38.112.134:6443
  name: cash-chan
contexts:
- context:
    cluster: cash-chan
    user: cash-chan-admin
  name: cash-chan
current-context: cash-chan
kind: Config
preferences: {}
users:
- name: cash-chan-admin
  user:
    token: pat here

# You can find the kubeconfig file for k3s typically at /etc/rancher/k3s/k3s.yaml
# Or not. May have changed. Check the docs.